version: '3.8'

volumes:
  logs:
    driver: local
  data:

services:
  db_app:
    container_name: app_db
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      SA_PASSWORD: "password"
      ACCEPT_EULA: "Y"
    volumes:
      - data:/var/opt/mssql
    ports:
      - "1433:1433"
  backend:
    tty: true
    container_name: api
    build:
        context: .
        dockerfile: Dockerfile
    volumes:
      - .:/go/src
    environment:
      - TZ=America/Sao_Paulo
      - SQLSERVER_DB_HOST=db_app
      - SQLSERVER_DB_USER=SA
      - SQLSERVER_DB_PASSWORD=password
      - SQLSERVER_DB_NAME=dbApp
    ports:
      - "5000:5000"
    depends_on:
      - db_app
    links:
      - db_app
