version: '3.8'

volumes:
  logs:
    driver: local
  data:

services:
  db_app:
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_DB: brickdb
      POSTGRES_USER: root
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
  backend:
    tty: true
    container_name: api
    build:
        context: .
        dockerfile: Dockerfile
    volumes:
      - .:/go/src
    environment:
      - TZ=America/Sao_Paulo
      - SQLSERVER_DB_HOST=db_app
      - SQLSERVER_DB_USER=SA
      - SQLSERVER_DB_PASSWORD=Brick@123
      - SQLSERVER_DB_NAME=dbApp
    ports:
      - "8083:8083"
    depends_on:
      - db_app
