package helper

const (
	ErrorShuttingDownServerConst    = "error shutting down server: %s"
	VehicleFieldCanNotBeEmptyConst  = "é necessário enviar %s do veículo"
	VehicleTypeIsNotInTheEnumConst  = "o tipo do veículo não é válido"
	UserFieldCanNotBeEmptyConst     = "é necessário enviar %s do usuário"
	EmailCanNotBeEmptyConst         = "é necessário enviar o email"
	EmailTooLongConst               = "o email ultrapassa o número máximo de caracteres"
	InvalidEmailFormatConst         = "formato inválido de email"
	InvalidLicensePlateFormatConst  = "formato inválido de placa de carro"
	InvalidRenavamFormatConst       = "renavam inválido"
	RenavamMustHaveOnlyNumbersConst = "o renavam deve conter apenas números"
	RenavamMustHave11digitsConst    = "o renavam deve conter 11 dígitos"
	InvalidCnpjFormatConst          = "cnpj inválido"
	CnpjMustHave14digitsConst       = "o cnpj deve conter 14 dígitos"
	VehicleAlreadyExistsConst       = "o veículo já existe"
	InformFieldConst                = "é necessário enviar %s"
	PolicyStatusInvalidConst        = "o status da apólice é inválido"
	PolicyFieldCanNotBeEmptyConst   = "é necessário enviar %s da apólice"
	PolicyNotFoundConst             = "apólice não encontrada"
	VehicleNotFoundConst            = "veículo não encontrado"
	CoverageNotFoundConst           = "cobertura não encontrada"
	UserlreadyExistsConst           = "o usuário já existe"
	CpfIsInvalidErrorConst          = "o cpf é inválido"
	InvalidCpfLengthErrorConst      = "o cpf não possui o tamanho correto"
	CpfShouldContainOnlyNumbersCont = "o cpf deve conter apenas números"
	VehicleAlreadyIsInPolicyConst   = "o veículo já está em uma apólice"
	CoverageAlreadyInPolicyConst    = "cobertura já vinculada a essa apólice"
)
